name: Deploy 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name:  Get latest code
      uses: actions/checkout@v2
    - name: Build Project
      run: npm install && npm run build
    - name: Deploy the build 
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.funtiontales.domains.swarthmore.edu
        username: admin@funtiontales.domains.swarthmore.edu
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./build/
        server-dir: /public_html
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/node_modules/**
